name: Deploy to Vertex

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Project
        run: uv sync --frozen

      - name: Trigger deployment
        run: |
          uv run app/agent_engine_app.py \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --location ${{ secrets.GCP_REGION }} \
            --set-env-vars="COMMIT_SHA=${{ github.sha }}" 