name: Deploy to Vertex

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Project
        run: uv sync --frozen

      - name: Prepare requirements.txt
        run: |
          uv export --no-hashes --no-header --no-dev --no-emit-project --frozen > .requirements.txt

      - name: Trigger deployment
        run: |
          uv run app/agent_engine_app.py \
            --agent-name sentoru-agent \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --location ${{ secrets.GCP_REGION }} \
            --set-env-vars="SAFETY_API_KEY=${{ secrets.SAFETY_API_KEY }},LLM_DEPLOYMENT=gemini-2.5-flash,VULN_RAG_CORPUS=${{ secrets.VULN_RAG_CORPUS }}" 