name: CI Job (Unit tests and linters)

on:
  workflow_call:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python
        uses: actions/setup-python@v5
      
      - name: Install Project
        run: uv sync --dev

      - name: Run pyright
        run: uv run pyright .

  ruff_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install Project
        run: uv sync --dev

      - name: Run Ruff check
        run: uv run ruff check --diff .

  ruff_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install Project
        run: uv sync --dev

      - name: Run Ruff check
        run: uv run ruff format --diff .

  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install Project
        run: uv sync --dev

      - name: Run Unittests
        run: uv run pytest ./tests/unit/
